### ISSUE TITLE
Documentation of otcextensions.sdk.Connection

### ISSUE THREAD

**Issue by mr-sicher** [opentelekomcloud/python-otcextensions#228]
We found that the documentation is missing for additional functions e.g. `search_images` (function of `otcextensions.sdk.Connection`) functionality.

Expected documentation about:
- `search_images` functionality
- arguments of the function `args=['self', 'name_or_id', 'filters'], varargs=None, keywords=None, defaults=(None, None)`

**Comment by gtema** [comment]
Sorry for late response.
This function is actually coming from OpenStackSDK https://opendev.org/openstack/openstacksdk/src/branch/master/openstack/cloud/_image.py#L51 where it is not documented. OTCE inherits from there and adds additional functions. Thus the real issue is that the function is not documented there. I will try to take care of that, however it will not be fast, since OpenStackSDK is currently in a restructuring phase without soon release.

Thanks for reporting.
