### ISSUE TITLE
Server Error: The backend server is unreachable

### ISSUE THREAD

**Issue by njgte** [opentelekomcloud/python-otcextensions#246]
When using otc-cli in a github action I (most of the time, but not always) get the error 'The backend server is unreachable'. In 80% of the runs this error occurs, in 20% the api calls are completed successfully. 

**My environment:** 
I am using the otc-cli to access the telekom API from a Github Action. 
The minimalised Github workflow is the following: 

```shell
name: test-run
on: [push, workflow_dispatch] ## run when triggered manually
jobs:
  test-run:
    name: Reproduce API issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: 'echo "$credentials" > switch_active_server/secure.yaml'
      shell: bash
      env:
        credentials: ${{secrets.OTC_CREDENTIALS}}
    - run: pip install -r switch_active_server/requirements.txt
    - run: cd switch_active_server && openstack --os-cloud otc floating ip list -f value && openstack --os-cloud otc floating ip list -f value && openstack --os-cloud otc loadbalancer member set --debug --weight 1 3d39f627-74ec-4c2c-b5cb-984d42673100 48f2b48e-4a55-41b3-ab5d-0c45528e9b7f
```

My requirements are:
```shell
otcextensions==0.24.2
python-openstackclient==5.6.0
```

**What I expected**
That I get no errors and the weight of the specified server is set to 1. 

**What actually happened**
I get the error as mentioned above and the "set"-command is not executed. 

I can not reproduce this error when running the calls locally. It only occurs when running this as a github action on a github runner. But still the log indicate that it is a server issue. 

Attached you find the logs for one of the failing runs.
[5_Run cd switch_active_server && openstack --os-cloud otc fl.txt](https://github.com/opentelekomcloud/python-otcextensions/files/7545589/5_Run.cd.switch_active_server.openstack.--os-cloud.otc.fl.txt)
Please let me know if you need any more information.  

**Update**
I cannot reproduce the issue when running only one `floating ip list` call before the `member set` call. I only get the error when running the `member` set call twice and then the `member set`.

**Comment by gtema** [comment]
Thanks for reporting.

Sadly this is a known issue which is not caused by this software, but rather the real backend implementation. We have reported this already some time ago, but still waiting for the fix to be deployed.

Some background: this is apparently an issue caused by some AntiDDoS security software in the backend which we are all waiting to be replaced. We also know that the issue only affects particular IP addresses from which requests are coming, therefore if you would be able to achieve using different IP address (and I know in this setup this is not going to be easy) - most likely the problem can be avoided.
