### ISSUE TITLE
Several openstack queries are not working

### ISSUE THREAD

**Issue by hadoopch** [opentelekomcloud/python-otcextensions#313]
Hi all,

several openstack queries are nor working

**1) openstack --os-cloud otc hypervisor list -vv**

```Error
START with options: --os-cloud otc hypervisor list -v
command: hypervisor list -> openstackclient.compute.v2.hypervisor.ListHypervisor (auth=True)
Using auth plugin: password
str' object has no attribute 'get'
END return value: 1
```

**2)  openstack --os-cloud otc domain list -v**
```Error
START with options: --os-cloud otc domain list -v
command: domain list -> openstackclient.identity.v3.domain.ListDomain (auth=True)
Using auth plugin: password
**Unrecognized schema in response body. (HTTP 404)**
END return value: 1
```

**3) openstack --os-cloud otc domain show <Domain-Name>-v**
```Error
command: domain show -> openstackclient.identity.v3.domain.ShowDomain (auth=True)
Using auth plugin: password
No domain with a name or ID of '5a607d13766d4dd5adfc56c10a65e9f8' exists.
END return value: 1
```
Here the Domain-Name is resolved but i can't get infos

**4) openstack --os-cloud otc user list -v**

```Error
START with options: --os-cloud otc user list -v
command: user list -> openstackclient.identity.v3.user.ListUser (auth=True)
Using auth plugin: password
You are not authorized to perform the requested action. (HTTP 403)
END return value: 1
```

Here i get an HTTP 403. But I am admin.

I have already talked to the huawei people.  The recommend me to open an issue here,.

Who can support.

Best regards

Uli

**Comment by gtema** [comment]
- domain list will not work, since no customer have permission to list domains
- domain show is having same issue. openstackclient is trying under the hood to list domains and then get details of the single one. List is not working, but also no details can be shown since this API is also not whitelisted for users (https://docs.otc.t-systems.com/api/iam/en-us_topic_0057845574.html)
- user list - being admin is not enough, it is required to get proper token which is the case when in clouds.yaml instead of project_name/id domain_name/id is being set (to the same value as the user_domain_name/id). This is called in OpenStack - domain scope token. This command is working perfectly fine for me right now with all latest version.
- hypervisor apis are not available on OTC either. I have no clue why Huawei people told you to ask us

**Comment by hadoopch** [comment]
Hi Artem,

thanks a lot.
At least listing user is working now.

Regards

Uli


Von: Artem Goncharov ***@***.***>
Gesendet: Montag, 17. Oktober 2022 10:17
An: opentelekomcloud/python-otcextensions ***@***.***>
Cc: Tehrani, Ulrich ***@***.***>; Author ***@***.***>
Betreff: Re: [opentelekomcloud/python-otcextensions] Several openstack queries are not working (Issue #313)


  *   domain list will not work, since no customer have permission to list domains
  *   domain show is having same issue. openstackclient is trying under the hood to list domains and then get details of the single one. List is not working, but also no details can be shown since this API is also not whitelisted for users (https://docs.otc.t-systems.com/api/iam/en-us_topic_0057845574.html)
  *   user list - being admin is not enough, it is required to get proper token which is the case when in clouds.yaml instead of project_name/id domain_name/id is being set (to the same value as the user_domain_name/id). This is called in OpenStack - domain scope token. This command is working perfectly fine for me right now with all latest version.
  *   hypervisor apis are not available on OTC either. I have no clue why Huawei people told you to ask us

**Comment by hadoopch** [comment]
Listing User is working now
